// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/hepengzheng/stock-state/pkg/config"
	"github.com/hepengzheng/stock-state/pkg/stockstate"
	"github.com/hepengzheng/stock-state/pkg/storage"
	"github.com/hepengzheng/stock-state/server"
)

// Injectors from wire.go:

func initApp(contextContext context.Context, configConfig *config.Config) (*server.StockServer, error) {
	client, err := NewEtcdClient(configConfig)
	if err != nil {
		return nil, err
	}
	stockStorage := storage.NewEtcdStockStorage(client)
	allocatorManager := stockstate.NewAllocatorManager(contextContext, client, stockStorage, configConfig)
	stockServer := server.NewServer(contextContext, allocatorManager)
	return stockServer, nil
}
